trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Home

parameters:
- name: wpa_supplicant_path
  default: $(WpaSupplicant.secureFilePath)
- name: openvpn_file_path
  default: $(OpenVPN.secureFilePath)
- name: username
  default: $(username)
- name: network
  default: $(network)
- name: ssh_public_key_path
  default: $(PublicKey.secureFilePath)
- name: hostname
  default: $(hostname)
- name: workspace_id
  default: $(workspace_id)
- name: workspace_key
  default: $(workspace_key)
- name: timezone
  default: $(timezone)
- name: image_url
  default:
- name: image_checksum
  default:
        
steps:
- task: DownloadSecureFile@1
  name: PublicKey
  displayName: Download public key
  inputs:
    secureFile: id_rsa.pub

- task: DownloadSecureFile@1
  name: WpaSupplicant
  displayName: Download wpa_supplicant.conf
  inputs:
    secureFile: wpa_supplicant.conf

- task: DownloadSecureFile@1
  name: OpenVPN
  displayName: Download azure.ovpn
  inputs:
    secureFile: azure.ovpn

- ${{ each parameter in parameters }}:
  - script: |
      VALUE=$([[ '${{ parameter.Value }}' == {* ]] && echo -n '${{ parameter.Value }}' || echo -n '"${{ parameter.Value }}"')
      echo "${{ parameter.Key }} = $VALUE" >> variables.auto.pkrvars.hcl
    displayName: Setting ${{ parameter.Key }} in Packer variables file

- script: |
    if [ -z "$(grep image_url variables.auto.pkrvars.hcl | cut -d'"' -f2)" ]; then
        IMAGE=$(curl -s 'https://downloads.raspberrypi.org/raspios_lite_armhf/images/' | grep 'href="raspios_lite_armhf-' | cut -d'"' -f8 | sort | tail -n1)
        IMAGE_NAME=$(curl -s "https://downloads.raspberrypi.org/raspios_lite_armhf/images/$IMAGE" | grep '.img.xz"' | cut -d'"' -f8)
        IMAGE_URL="https://downloads.raspberrypi.org/raspios_lite_armhf/images/${IMAGE}${IMAGE_NAME}"
        IMAGE_SHA256="sha256:$(curl -s "https://downloads.raspberrypi.org/raspios_lite_armhf/images/$IMAGE/${IMAGE_NAME}.sha256" | cut -d' ' -f1)"
    
        sed -i "s#image_url = \"\"#image_url = \"$IMAGE_URL\"#" variables.auto.pkrvars.hcl
        sed -i "s#image_checksum = \"\"#image_checksum = \"$IMAGE_SHA256\"#" variables.auto.pkrvars.hcl
    fi
    
    cat variables.auto.pkrvars.hcl
  displayName: Set lastest versions

- script: |
    sudo apt-get -qq -o=Dpkg::Use-Pty=0 install -y qemu-user-static kpartx qemu binfmt-support e2fsprogs dosfstools libarchive-tools
    
    packer init image.pkr.hcl

    sudo packer build -var-file=variables.auto.pkrvars.hcl image.pkr.hcl
  displayName: Build image
  failOnStderr: true
# Not working, open an issue on Packer
#  env:
#    ${{ each parameter in parameters }}:
#      PKR_VAR_${{ parameter.Key }}: ${{ parameter.Value }}
#    #PKR_VAR_image_url: $(SET VARIABLE IN Set lastest versions TASK)
#    #PKR_VAR_image_checksum: $(SET VARIABLE IN Set lastest versions TASK)

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/output-raspbian/image
    publishLocation: pipeline