trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  wifi_name: SSID
  wifi_password: WIFIPASS

steps:
- task: DownloadSecureFile@1
  name: PublicKey
  displayName: 'Download public key'
  inputs:
    secureFile: 'id_rsa.pub'

- script: |
    # curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    # sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    # apt-get update
    # sudo apt-get install -y packer
    
    sudo apt-get install -y qemu-user-static git wget zip unzip build-essential kpartx qemu binfmt-support e2fsprogs dosfstools

    export PACKER_RELEASE="1.6.6"
    
    wget https://releases.hashicorp.com/packer/${PACKER_RELEASE}/packer_${PACKER_RELEASE}_linux_amd64.zip

    unzip packer_${PACKER_RELEASE}_linux_amd64.zip

    PATH=$PATH:$(pwd)

    export PACKER_ARM_BUILDER_VERSION="0.1.6"

    wget https://github.com/solo-io/packer-builder-arm-image/releases/download/v${PACKER_ARM_BUILDER_VERSION}/packer-builder-arm-image

    chmod +x packer-builder-arm-image

    # Find latest and pass as argument https://downloads.raspberrypi.org/raspios_lite_armhf/images/

    sudo ./packer build \
        -var "wifi_name=$(wifi_name)" \
        -var "wifi_password=$(wifi_password)" \
        -var "ssh_pub_key_path=$(PublicKey.secureFilePath)" \
        packer-raspberry-pi-os-lite.json

    zip -r rpi-arm-image.zip output-arm-image/image
    
    du -hs output-arm-image/image
    du -hs rpi-arm-image.zip
  displayName: 'Build image'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/raspberry-pi-os-image-builder/rpi-arm-image.zip'
    publishLocation: 'pipeline'