trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Home

parameters:
- name: wpa_supplicant_path
  default: $(WpaSupplicant.secureFilePath)
- name: openvpn_file_path
  default: $(OpenVPN.secureFilePath)
- name: username
  default: $(username)
- name: network
  default: $(network)
- name: ssh_public_key_path
  default: $(PublicKey.secureFilePath)
- name: hostname
  default: $(hostname)
- name: workspace_id
  default: $(workspace_id)
- name: workspace_key
  default: $(workspace_key)
- name: timezone
  default: $(timezone)
- name: exclude_plugins
  default: $(exclude_plugins)
- name: motion_password
  default: $(motion_password)
        
steps:
# Run Pulumi steps only when motion is included
- task: Pulumi@1
  displayName: Set configuration
  inputs:
    azureSubscription: Pulumi backend
    command: config
    args: set notificationEmail $(notification_email)
    stack: dev
    createStack: true
    cwd: cctv/infrastructure
    loginArgs: azblob://stacks?storage_account=$(pulumi_backend_storage_account)
  
- task: Pulumi@1
  displayName: Deploy infrastructure
  inputs:
    azureSubscription: Pulumi backend
    command: up
    args: --yes
    stack: dev
    createStack: true
    cwd: cctv/infrastructure
    loginArgs: azblob://stacks?storage_account=$(pulumi_backend_storage_account)

- script: |
    pulumi stack output PrivateKey --show-secrets > id_rsa
    echo "##vso[task.setvariable variable=storage_account_name;]$(pulumi stack output StorageAccount)"
    echo "##vso[task.setvariable variable=storage_username;]$(pulumi config get username)"
  displayName: Export SSH key and storage account info
  
- task: DownloadSecureFile@1
  name: PublicKey
  displayName: Download public key
  inputs:
    secureFile: id_rsa.pub

- task: DownloadSecureFile@1
  name: WpaSupplicant
  displayName: Download wpa_supplicant.conf
  inputs:
    secureFile: wpa_supplicant.conf

- task: DownloadSecureFile@1
  name: OpenVPN
  displayName: Download azure.ovpn
  inputs:
    secureFile: azure.ovpn

- ${{ each parameter in parameters }}:
  - script: |
      VALUE=$([[ '${{ parameter.Value }}' == {* ]] && echo -n '${{ parameter.Value }}' || echo -n '"${{ parameter.Value }}"')
      echo "${{ parameter.Key }} = $VALUE" >> variables.auto.pkrvars.hcl
    displayName: Setting ${{ parameter.Key }} in Packer variables file

- script: |
    IMAGE=$(curl -s 'https://downloads.raspberrypi.org/raspios_lite_armhf/images/' | grep 'href="raspios_lite_armhf-' | cut -d'"' -f8 | sort | tail -n1)
    IMAGE_NAME=$(curl -s "https://downloads.raspberrypi.org/raspios_lite_armhf/images/$IMAGE" | grep '.img.xz"' | cut -d'"' -f8)
    IMAGE_URL="https://downloads.raspberrypi.org/raspios_lite_armhf/images/${IMAGE}${IMAGE_NAME}"
    IMAGE_SHA256="sha256:$(curl -s "https://downloads.raspberrypi.org/raspios_lite_armhf/images/$IMAGE/${IMAGE_NAME}.sha256" | cut -d' ' -f1)"

    echo "image_url = \"$IMAGE_URL\"" >> variables.auto.pkrvars.hcl
    echo "image_checksum = \"$IMAGE_SHA256\"" >> variables.auto.pkrvars.hcl
    
    echo "storage_username = $(storage_username)" >> variables.auto.pkrvars.hcl
    echo "storage_account_name = $(storage_account_name)" >> variables.auto.pkrvars.hcl
    
    cat variables.auto.pkrvars.hcl
  displayName: Set lastest versions of image variables and storage

- script: |
    sudo apt-get -qq -o=Dpkg::Use-Pty=0 install -y qemu-user-static kpartx qemu binfmt-support e2fsprogs dosfstools libarchive-tools
    
    packer init image.pkr.hcl

    sudo packer build -var-file=variables.auto.pkrvars.hcl image.pkr.hcl
  displayName: Build image
  failOnStderr: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/output-raspbian/image
    publishLocation: pipeline