# TODO:
# Fix key upload
# Remove password, use only SSH key
# Fail pipeline on packer failure

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Home

parameters:
- name: wifi_ssid
  default: $(wifi_ssid)
- name: wifi_password
  default: $(wifi_password)
- name: username
  default: $(username)
- name: ssh_public_key_path
  default: $(PublicKey.secureFilePath)

variables:
  packer_version: 1.6.6
  packer_arm_builder_version: 0.1.6
        
steps:
- task: DownloadSecureFile@1
  name: PublicKey
  displayName: 'Download public key'
  inputs:
    secureFile: 'id_rsa.pub'

- script: |
    # curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    # sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    # apt-get update
    # sudo apt-get install -y packer
    
    sudo apt-get install -y qemu-user-static git wget zip unzip build-essential kpartx qemu binfmt-support e2fsprogs dosfstools
    
    wget https://releases.hashicorp.com/packer/${{ variables.packer_version }}/packer_${{ variables.packer_version }}_linux_amd64.zip

    unzip packer_${{ variables.packer_version }}_linux_amd64.zip

    PATH=$PATH:$(pwd)

    wget https://github.com/solo-io/packer-builder-arm-image/releases/download/v${{ variables.packer_arm_builder_version }}/packer-builder-arm-image

    chmod +x packer-builder-arm-image

    # Find latest and pass as argument https://downloads.raspberrypi.org/raspios_lite_armhf/images/

    sudo ./packer build \
        ${{ each parameter in parameters }}:
          -var "${{ parameter.Key }}=${{ parameter.Value }}" \
        packer-raspberry-pi-os-lite.json

    du -hs output-arm-image/image

    xz -v output-arm-image/image
    
    du -hs image.xz
  displayName: 'Build image'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/rpi-arm-image.zip'
    publishLocation: 'pipeline'