# TODO:
# Fix key upload
# Remove password, use only SSH key
# Fail pipeline on packer failure

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Home
- name: packer_version
  value: 1.6.6
- name: packer_arm_builder_version
  value: 0.1.6

parameters:
- name: wifi_ssid
  default: $(wifi_ssid)
- name: wifi_password
  default: $(wifi_password)
- name: username
  default: $(username)
- name: ip
  default: $(ip)
- name: subnet
  default: $(subnet)
- name: router
  default: $(router)
- name: ssh_public_key_path
  default: $(PublicKey.secureFilePath)
- name: image_url
  default: https://downloads.raspberrypi.org/raspios_lite_armhf/images/raspios_lite_armhf-2022-09-26/2022-09-22-raspios-bullseye-armhf-lite.img.xz
- name: image_checksum
  default: sha256:9bf5234efbadd2d39769486e0a20923d8526a45eba57f74cda45ef78e2b628da
        
steps:
- task: DownloadSecureFile@1
  name: PublicKey
  displayName: 'Download public key'
  inputs:
    secureFile: 'id_rsa.pub'

- script: echo -n "{" > variables.json
  displayName: Open brackets in Packer variables file
- ${{ each parameter in parameters }}:
  - script: |
      echo -n '"${{ parameter.Key }}": "${{ parameter.Value }}",' >> variables.json
    displayName: Setting ${{ parameter.Key }} in Packer variables file
- script: |
    truncate -s -1 variables.json
    echo "}" >> variables.json
  displayName: Close brackets in Packer variables file

- script: |
    # curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
    # sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    # apt-get update
    # sudo apt-get install -y packer
    
    sudo apt-get -qq -o=Dpkg::Use-Pty=0 install -y qemu-user-static git wget zip unzip build-essential kpartx qemu binfmt-support e2fsprogs dosfstools
    
    wget -q https://releases.hashicorp.com/packer/${{ variables.packer_version }}/packer_${{ variables.packer_version }}_linux_amd64.zip

    unzip -qq packer_${{ variables.packer_version }}_linux_amd64.zip

    PATH=$PATH:$(pwd)

    wget -q https://github.com/solo-io/packer-builder-arm-image/releases/download/v${{ variables.packer_arm_builder_version }}/packer-builder-arm-image

    chmod +x packer-builder-arm-image

    # Find latest and pass as argument https://downloads.raspberrypi.org/raspios_lite_armhf/images/
    
    sudo ./packer build -var-file=variables.json packer-raspberry-pi-os-lite.json

    du -hs output-arm-image/image

    xz -v output-arm-image/image
    
    du -hs image.xz
  displayName: 'Build image'
# Presumably the Packer version supported by the
# arm builder does not support PKR_VAR_* for setting 
# variables; add this back when we can upgrade Packer.
#  env:
#    ${{ each parameter in parameters }}:
#      PKR_VAR_${{ parameter.Key }}: ${{ parameter.Value }}

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/rpi-arm-image.zip'
    publishLocation: 'pipeline'