trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: Home
- name: packer_version
  value:
- name: packer_arm_builder_version
  value:

parameters:
- name: wpa_supplicant_path
  default: $(WpaSupplicant.secureFilePath)
- name: username
  default: $(username)
- name: ip
  default: $(ip)
- name: subnet
  default: $(subnet)
- name: router
  default: $(router)
- name: ssh_public_key_path
  default: $(PublicKey.secureFilePath)
- name: hostname
  default: $(hostname)
- name: image_url
  default:
- name: image_checksum
  default:
        
steps:
- task: DownloadSecureFile@1
  name: PublicKey
  displayName: Download public key
  inputs:
    secureFile: id_rsa.pub

- task: DownloadSecureFile@1
  name: WpaSupplicant
  displayName: Download wpa_supplicant.conf
  inputs:
    secureFile: wpa_supplicant.conf

- script: echo -n "{" > variables.json
  displayName: Open brackets in Packer variables file
- ${{ each parameter in parameters }}:
  - script: |
      echo -n "\"${{ parameter.Key }}\": $(echo -n '${{ parameter.Value }}' | jq -Rsa .)," >> variables.json
    displayName: Setting ${{ parameter.Key }} in Packer variables file
- script: |
    truncate -s -1 variables.json
    echo "}" >> variables.json
  displayName: Close brackets in Packer variables file

- script: |
    if [ -z "$(jq .image_url variables.json -r)" ]; then
        IMAGE=$(curl -s 'https://downloads.raspberrypi.org/raspios_lite_armhf/images/' | grep 'href="raspios_lite_armhf-' | cut -d'"' -f8 | sort | tail -n1)
        IMAGE_NAME=$(curl -s "https://downloads.raspberrypi.org/raspios_lite_armhf/images/$IMAGE" | grep '.img.xz"' | cut -d'"' -f8)
        IMAGE_URL="https://downloads.raspberrypi.org/raspios_lite_armhf/images/${IMAGE}${IMAGE_NAME}"
        IMAGE_SHA256="sha256:$(curl -s "https://downloads.raspberrypi.org/raspios_lite_armhf/images/$IMAGE/${IMAGE_NAME}.sha256" | cut -d' ' -f1)"
    
        jq ".image_url = \"$IMAGE_URL\" | .image_checksum = \"$IMAGE_SHA256\"" variables.json > temp.json && mv temp.json variables.json
    fi
    
    if [ -z "${{ variables.packer_version }}" ]; then
        echo "##vso[task.setvariable variable=packer_version]$(curl -s https://checkpoint-api.hashicorp.com/v1/check/packer | jq -r .current_version)"
    fi
    
    if [ -z "${{ variables.packer_arm_builder_version }}" ]; then
        GITHUB_TAG="$(curl -s "https://api.github.com/repos/solo-io/packer-plugin-arm-image/releases/latest" | jq -r .tag_name)"
        echo "##vso[task.setvariable variable=packer_arm_builder_version]${GITHUB_TAG:1}"
    fi
    
    cat variables.json
    
    echo "Packer version: $[packer_version]"
    echo "Packer ARM image builder version: $[packer_arm_builder_version]"
  displayName: Set lastest versions

- script: |
    sudo apt-get -qq -o=Dpkg::Use-Pty=0 install -y qemu-user-static kpartx qemu binfmt-support e2fsprogs dosfstools libarchive-tools
    
    wget -qO- https://releases.hashicorp.com/packer/$(packer_version)/packer_$(packer_version)_linux_amd64.zip | bsdtar xf -
    
    wget -qO- https://github.com/solo-io/packer-builder-arm-image/releases/download/v$(packer_arm_builder_version)/packer-plugin-arm-image_v$(packer_arm_builder_version)_x5.0_linux_amd64.zip | bsdtar xf -

    chmod +x packer*

    env
    
    echo "################################"
    
    export -p

    sudo ./packer build image.pkr.hcl
  displayName: Build image
  failOnStderr: true
  env:
    ${{ each parameter in parameters }}:
      PKR_VAR_${{ parameter.Key }}: ${{ parameter.Value }}

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)/output-arm-image/image
    publishLocation: pipeline